spring:
  application:
    name: jokes

server:
  port: 8070

gemini:
  api:
    apiKey: ${GEMINI_API_KEY}
    apiUrl: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
