spring:
  application:
    name: jokes

server:
  port: ${PORT:8080}

gemini:
  api:
    api-key: ${GEMINI_API_KEY}
    api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent
